name: Exemplo de CI

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test With Maven
        run: mvn test

      - name: Build with Maven
        run: mvn -B package -DskipTests
